import os
import uuid
import logging
from pathlib import Path
from typing import Dict, Any, Optional
from app.config import settings
from app.database import supabase

logger = logging.getLogger("media_storage")

class MediaStorageService:
    """
    Abstract Media Storage Service:
    - Automatically streams uploads to Supabase Object Storage ('media-assets' bucket)
    - Fallback to local filesystem storage in backend/static/uploads/ when offline/mock
    - Returns high-availability public CDN/HTTPS URLs
    """
    
    def __init__(self):
        self.upload_dir = Path(__file__).parent.parent.parent.parent / "static" / "uploads"
        self.upload_dir.mkdir(parents=True, exist_ok=True)
        self.bucket_name = "media-assets"

    def save_file(self, contents: bytes, filename: str, content_type: str, request_base_url: Optional[str] = None) -> Dict[str, Any]:
        unique_name = f"media_{int(uuid.uuid4().int % 100000000000)}_{uuid.uuid4().hex[:8]}{Path(filename).suffix.lower()}"
        
        # 1. Attempt Supabase Cloud Object Storage upload
        if supabase:
            try:
                # Content-Type header option for proper browser rendering
                file_options = {"content-type": content_type, "upsert": "true"}
                supabase.storage.from_(self.bucket_name).upload(
                    path=unique_name,
                    file=contents,
                    file_options=file_options
                )
                public_url = supabase.storage.from_(self.bucket_name).get_public_url(unique_name)
                # Clean trailing query param if generated by get_public_url
                if public_url.endswith("?"):
                    public_url = public_url[:-1]

                logger.info(f"Successfully uploaded media to Supabase storage [{self.bucket_name}/{unique_name}]: {public_url}")
                return {
                    "unique_filename": unique_name,
                    "storage_path": f"supabase://{self.bucket_name}/{unique_name}",
                    "public_url": public_url,
                    "size": len(contents)
                }
            except Exception as e:
                logger.warning(f"Supabase storage upload failed ({e}). Falling back to local filesystem.")

        # 2. Local filesystem fallback
        dest_path = self.upload_dir / unique_name
        with open(dest_path, "wb") as f:
            f.write(contents)

        configured_base = settings.MEDIA_PUBLIC_BASE_URL.rstrip("/")
        fallback_base = (request_base_url or "http://127.0.0.1:8000").rstrip("/")
        base_url = configured_base if configured_base and "127.0.0.1" not in configured_base and "localhost" not in configured_base else fallback_base
        public_url = f"{base_url}/static/uploads/{unique_name}"

        return {
            "unique_filename": unique_name,
            "storage_path": str(dest_path),
            "public_url": public_url,
            "size": len(contents)
        }

media_storage = MediaStorageService()

